### ISSUE TITLE
Console errors complaining about blob://url

### ISSUE THREAD

**Issue by jolamar** [duosecurity/duo_web_sdk#10]
Console gives error about file inject.preload.js:373 which is:

```
if (document instanceof HTMLDocument)
{
  let sandbox = window.frameElement &&
                window.frameElement.getAttribute("sandbox");

  if (typeof sandbox != "string" || /(^|\s)allow-scripts(\s|$)/i.test(sandbox))
  {
    let script = document.createElement("script");
    script.type = "application/javascript";
    script.async = false;
    // Firefox 58 only bypasses site CSPs when assigning to 'src'.
    let url = URL.createObjectURL(new Blob([
      "(" + injected + ")('" + randomEventName + "');"
    ]));
    script.src = url;
    document.documentElement.appendChild(script);
    document.documentElement.removeChild(script);
    URL.revokeObjectURL(url);
  }
}
```
specifically this line `document.documentElement.appendChild(script);`=
<img width="640" alt="screen shot 2018-07-17 at 6 28 47 am" src="https://user-images.githubusercontent.com/1017119/42817222-b26c7360-898a-11e8-9843-717e3f303b02.png">

**Comment by xdesai** [comment]
Hi Josh!
We believe that this error is not coming from us, but is coming from some third party JS.
Specifically AdBlock
https://issues.adblockplus.org/ticket/6744
https://github.com/adblockplus/adblockpluschrome/blob/5b9a51852b9a89d5dfe063afec0e8d7330fcc4e6/inject.preload.js

AdBlock seems to give this error when loading a page with an iframe which is happening here because of the Duo Frame

**Comment by jolamar** [comment]
Good call!
