### ISSUE TITLE
Publish To NPM

### ISSUE THREAD

**Issue by janstadt** [duosecurity/duo_web_sdk#15]
Is there a reason why you havent published this artifact to NPM? We would like to use this package but due to our build tools/networking/artifcatory/etc we cannot pull down github url style packages from our packages.json file. Would be really nice if you just published this to NPM so it would work the way that most packages do.

**Comment by toquetoquequiestla** [comment]
Agreed, it's a shame because that package is super handy. I think the easy way to go would be to fork and publish under your own registry if the license allows to do so. I'm curious to know if you went that way @janstadt or did you ended up using the script tags?

**Comment by janstadt** [comment]
We just committed it to our repo unfortunately. It doesnt seem like it gets regular maintenance so we just made the (crappy) decision to have it in our repo and bundle it with our other static content. I do agree tho that DUO should just push this to npm and call it a day.

**Comment by raydenx** [comment]
+1 for publishing the artifact to NPM registry.

**Comment by ptanaji-cb** [comment]
Is there a plan to publish to npm repository? @subyraman or any other maintainer for this repo, can we get some confirmation?

**Comment by AaronAtDuo** [comment]
@ptanaji-cb and others who have chimed in...
There are currently no plans to publish this to NPM, because Duo is moving to a new, OIDC-based flow for the Duo prompt, called the Universal Prompt, which makes this obsolete.  

In addition to being a more user- and administrator-friendly flow, it should be simpler to add to your own web applications because applications will no longer need to host or serve the Duo prompt - users will be redirected to Duo for the authentication prompt.  We encourage all new integrations to use the Universal Prompt.

You can read more about the Universal Prompt and how to migrate to it at https://duo.com/docs/universal-prompt-update-guide
Our OIDC-based API for the Universal Prompt is at https://duo.com/docs/oauthapi if you want to integrate it into an already-existing OIDC flow
We plan to create a NodeJS Universal Prompt SDK soon, to join our Python, Java, and PHP SDKs.  See https://duo.com/docs/duoweb for more details.
